package AppPackage2;


import Barchart.*;
import ObjectStatistik.ObjectXcle;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JPanel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salman Al Hafizh
 */
public class BarChart extends javax.swing.JFrame {
    /**
     * Creates new form BarChart
     */
    public BarChart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = createBarChartPanel1();
        jPanel4 = createPieChartPanel1();
        jPanel5 = createPieChartPanel2();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//     public static int countKecamatanstatic (String kec) {
//      FileInputStream xcleFile = new FileInputStream(new File("src\\Object\\data_terbaru.xlsx"));
//      String kecamatan;
//      
//      XSSFWorkbook workbook = new XSSFWorkbook(xcleFile);
//      XSSFSheet spreadsheet = workbook.getSheetAt(0); //Read sheet pertama
//      Iterator < Row >  rowIterator = spreadsheet.iterator();
//      rowIterator.next();
//      
//      while (rowIterator.hasNext()){
//          Row currentRow = rowIterator.next();
//          
//          Cell kecam = currentRow.getCell(17);
//          
//          kecamatan=kecam.getStringCellValue();
//          if (str){
//               jumlah +=1;
//          }
//      }
//        
//      return jumlah;
//    }

    // Bar Chart
    public static JPanel createBarChartPanel1() {
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        String[] kecamatan={"Andir","Antapani","Arcamanik","Bandung Kidul","BandungKulon","Bandung Wetan","Batununggal",
            "Buah Batu","Cibeunying Kaler","Cibeunying Kidul","Cibiru","Cimenyan","Coblong",
            "Dayeuhkolot","Gedebage","Kiaracondong","Lengkong","Panyileukan","Parongpong","Regol","Sukajadi",
            "Ujung Berung"};
        
        int[] jumlah = {10, 47, 4, 7, 1, 62, 6, 35, 3, 6, 1, 1, 39, 4, 9, 22, 14, 2, 2, 1, 1, 1};

        for (int i = 0; i < 22; i++) {
            data e = new data();
            e.setInfo(jumlah[i]);
            e.setTitle(kecamatan[i]);
            daftar.add(i, e);
        }

        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }

        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);

        return new ChartPanel(chart);
    }
    
    public static JPanel createBarChartPanel2(){
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }
        
        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);
        
        return new ChartPanel(chart);
    }
    
    public static JPanel createBarChartPanel3(){
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }
        
        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);
        
        return new ChartPanel(chart);
    }

    // Pie Chart
    public static JPanel createPieChartPanel1() {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        List<data> daftar = new ArrayList<>();

        for (int i = 0; i < 3; i++) {
            data e = new data();
            if (i == 0) {
                e.setTitle("Campuran");
                e.setInfo(151);
            } else if (i == 1) {
                e.setTitle("Putri");
                e.setInfo(69);
            } else {
                e.setTitle("Putra");
                e.setInfo(59);
            }
            daftar.add(i, e);
        }

        for (int i = 0; i < daftar.size(); i++) {
            pieDataset.setValue(daftar.get(i).getTitle(), daftar.get(i).getInfo());
        }
        JFreeChart chart = ChartFactory.createPieChart3D("Kost Berdasarkan Gender", pieDataset, true, true, true);

        return new ChartPanel(chart);
    }
    
    public static JPanel createPieChartPanel2() {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        List<data> daftar = new ArrayList<>();

        for (int i = 0; i < 10; i++) {
            data e = new data();
            if (i == 0) {
                e.setInfo(146);
                e.setTitle("< 500.000 ");
            } else if (i == 1) {
                e.setInfo(58);
                e.setTitle("500.000 - 1.000.000");
            } else if (i == 2) {
                e.setInfo(24);
                e.setTitle("1.000.000 - 1.500.000");
            } else if (i == 3) {
                e.setInfo(7);
                e.setTitle("1.500.000 - 2.000.000");
            } else {
                e.setInfo(8);
                e.setTitle("> 2.000.000");
            }
            daftar.add(i, e);
        }
        for (int i = 0; i< daftar.size (); i++) {
            pieDataset.setValue(daftar.get(i).getTitle(), daftar.get(i).getInfo());
        }
        JFreeChart chart = ChartFactory.createPieChart3D("Kost Berdasarkan Range Harga", pieDataset, true, true, true);

        return new ChartPanel(chart);
    }
    
    static List<ObjectXcle> bacaData = new ArrayList<>();
    
//    public List<ObjectXcle> ReadExcel(int no_sheet) throws IOException {
//        FileInputStream xcleFile = new FileInputStream(new File("src\\Object\\Data.xlsx"));
//
//        XSSFWorkbook workbook = new XSSFWorkbook(xcleFile);
//        XSSFSheet spreadsheet = workbook.getSheetAt(no_sheet); //Read sheet pertama
//        Iterator < Row >  rowIterator = spreadsheet.iterator();
//        rowIterator.next();
//
//        while (rowIterator.hasNext()){
//            Row currentRow = rowIterator.next();
//
//            Cell id = currentRow.getCell(0);
//            Cell jumlah = currentRow.getCell(1);
//
//            ObjectXcle str = new ObjectXcle();
//            str.setJumlah((int)jumlah.getNumericCellValue());
//            str.setId(id.getStringCellValue());
//
//            bacaData.add(str);
//        }
//
//          return bacaData;
//    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarChart().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}