/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage2;

import java.awt.Point;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class FormSignUp extends javax.swing.JFrame {

    private static final String EXCEL_FILE_LOCATION = "src/data/UserData.xls";
    private String namaDepan;
    private String namaBelakang;
    private String password;
    private String alamat;
    private String jenisAkun;

    public FormSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dragArea = new javax.swing.JPanel();
        labelFirstName = new javax.swing.JLabel();
        labelFirstName1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragArea.setBackground(new java.awt.Color(255, 255, 255));
        dragArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragAreaMouseDragged(evt);
            }
        });
        dragArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dragAreaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout dragAreaLayout = new javax.swing.GroupLayout(dragArea);
        dragArea.setLayout(dragAreaLayout);
        dragAreaLayout.setHorizontalGroup(
            dragAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        dragAreaLayout.setVerticalGroup(
            dragAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(dragArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 20));

        labelFirstName.setText("Nama Belakang");
        jPanel1.add(labelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        labelFirstName1.setText("Nama Depan");
        jPanel1.add(labelFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaDepan(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaBelakang(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, -1));

        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamat(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 290, -1));

        jLabel2.setText("Alamat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel3.setText("Jenis Akun");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jRadioButton1.setText("Pemilik Kost");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPemilikKos(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jRadioButton2.setText("Pencari Kost");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPencariKos(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("KosQu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBuatAkunMouseClicked(evt);
            }
        });

        jLabel4.setText("Buat Akun");
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelBuatAkun(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 100, 40));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Delete_32px_4.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/formsignup.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        //@author Imanda_Syahrul_Ramadhan
        exitFrame(FormSignUp.this);

    }//GEN-LAST:event_exitMousePressed

    private void dragAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragAreaMouseDragged
        // TODO add your handling code here:
        Point currCoords = evt.getLocationOnScreen();
        FormSignUp.this.setLocation(currCoords.x - compCoords.x, currCoords.y - compCoords.y);
    }//GEN-LAST:event_dragAreaMouseDragged

    private void dragAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragAreaMousePressed
        // TODO add your handling code here:
        compCoords = evt.getPoint();
    }//GEN-LAST:event_dragAreaMousePressed

    private void dragAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragAreaMouseReleased
        // TODO add your handling code here:
        compCoords = null;
    }//GEN-LAST:event_dragAreaMouseReleased

    private void jTextFieldNamaBelakang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaBelakang
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaBelakang

    private void jTextFieldNamaDepan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaDepan
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaDepan

    private void jTextFieldAlamat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamat
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamat

    private void jRadioButtonPemilikKos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPemilikKos
        setJenisAkun("Pemilik");
    }//GEN-LAST:event_jRadioButtonPemilikKos

    private void jRadioButtonPencariKos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPencariKos
        setJenisAkun("Pencari");
    }//GEN-LAST:event_jRadioButtonPencariKos

    private void jLabelBuatAkun(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelBuatAkun

    }//GEN-LAST:event_jLabelBuatAkun

    private void jPanelBuatAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuatAkunMouseClicked

        try {
            setNamaDepan(jTextField1.getText());
            setNamaBelakang(jTextField2.getText());
            setPassword(jPasswordField1.getText());
            setAlamat(jTextField3.getText());

            System.out.println(getNamaDepan());
            System.out.println(getNamaBelakang());
            System.out.println(getPassword());
            System.out.println(getAlamat());
            System.out.println(getJenisAkun());
            ProcessAndWriteExcelFile();
        } catch (IOException | InvalidFormatException ex) {
            System.out.println("GAGAL MENJALANKAN ProcessAndWriteExcelFile()");
        }
    }

    public void ProcessAndWriteExcelFile() throws IOException, InvalidFormatException {

        String isi;
        int i = 1;

        FileInputStream fis = new FileInputStream("src/data/UserData.xlsx");
//        Workbook wb = WorkbookFactory.create(fis);
        Workbook wb = new XSSFWorkbook(fis);
        Sheet sh = wb.getSheetAt(0);
        int noOfRow = sh.getLastRowNum();
        System.out.println("no of row : " + noOfRow);

        Row row = sh.getRow(i);
        System.out.println("Row row = sh.getRow(i))");
        Cell cell = row.getCell(0);
//        System.out.println("Nama depan : " + isi);
        isi = cell.getStringCellValue();
//        System.out.println("Nama depan : " + isi);
        while (isi.length() > 1) {
            System.out.println("Username - database : " + row.getCell(0));
            System.out.println("Password - database : " + row.getCell(1));
            row = sh.getRow(++i);
            cell = row.getCell(0);
            isi = cell.getStringCellValue();
        }
        System.out.println("ISI : " + isi);

        //cell 0
        cell.setCellType(Cell.CELL_TYPE_STRING);
        cell.setCellValue(getNamaDepan());
        //cell 1
        cell = row.createCell(1);
        cell.setCellType(Cell.CELL_TYPE_STRING);
        cell.setCellValue(getPassword());

        cell = row.createCell(2);
        cell.setCellType(Cell.CELL_TYPE_STRING);
        cell.setCellValue(getJenisAkun());

        cell = row.createCell(3);
        cell.setCellType(Cell.CELL_TYPE_STRING);
        cell.setCellValue(getNamaDepan() + " " + getNamaBelakang());

        cell = row.createCell(4);
        cell.setCellType(Cell.CELL_TYPE_STRING);
        cell.setCellValue(getAlamat());

        System.out.println(cell.getStringCellValue());
        try (FileOutputStream fos = new FileOutputStream("src/data/UserData.xlsx")) {
            wb.write(fos);
            fos.flush();
        }
        
        exitFrame(FormSignUp.this);
        CreateDialogFromOptionPane();
        System.out.println("Done");
    }//GEN-LAST:event_jPanelBuatAkunMouseClicked

    void exitFrame(JFrame frame) {
        frame.dispose();
    }

    static Point compCoords;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSignUp().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel dragArea;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelFirstName1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the namaDepan
     */
    public String getNamaDepan() {
        return namaDepan;
    }

    /**
     * @param namaDepan the namaDepan to set
     */
    public void setNamaDepan(String namaDepan) {
        this.namaDepan = namaDepan;
    }

    /**
     * @return the namaBelakang
     */
    public String getNamaBelakang() {
        return namaBelakang;
    }

    /**
     * @param namaBelakang the namaBelakang to set
     */
    public void setNamaBelakang(String namaBelakang) {
        this.namaBelakang = namaBelakang;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the alamat
     */
    public String getAlamat() {
        return alamat;
    }

    /**
     * @param alamat the alamat to set
     */
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    /**
     * @return the jenisAkun
     */
    public String getJenisAkun() {
        return jenisAkun;
    }

    /**
     * @param jenisAkun the jenisAkun to set
     */
    public void setJenisAkun(String jenisAkun) {
        this.jenisAkun = jenisAkun;
    }

    private void CreateDialogFromOptionPane() {
        
        JFrame parent = new JFrame();
        String show;
        String pass = getPassword();
        show = "Registration COMPLETE !\n"
                + "Your Username : " + getNamaDepan() + "\n"
                + "Your Password : " + pass.substring(0, 2);
        for(int i=0; i < pass.length()-2; i++){
            show += "*";
        }
        JOptionPane.showMessageDialog(parent, show);
    }
}
