/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage2;

import java.awt.Color;
import java.awt.Point;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Ahmad_Aji_Naufal_Ali
 */
public class StartGUI extends javax.swing.JFrame {

    private static final String EXCEL_FILE_LOCATION = "src/data/UserData.xls";
    private String namaDepan;
    private String namaBelakang;
    private String password;
    private String alamat;
    private String jenisAkun;

    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        judulApp = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        PanelSignIn = new javax.swing.JPanel();
        Loggin = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jUsername = new javax.swing.JFormattedTextField();
        jPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        buttonSignin = new javax.swing.JButton();
        PanelSignUP = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        Loggin1 = new javax.swing.JLabel();
        PanelStatistic = new javax.swing.JPanel();
        iconAbout1 = new javax.swing.JLabel();
        about1 = new javax.swing.JLabel();
        PanelAbout = new javax.swing.JPanel();
        iconAbout = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        homepage = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        deskripsi1 = new javax.swing.JLabel();
        deskripsi2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judulApp1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(165, 178, 243));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulApp.setBackground(new java.awt.Color(0, 51, 102));
        judulApp.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        judulApp.setForeground(new java.awt.Color(255, 255, 255));
        judulApp.setText("KosQu");
        sidePanel.add(judulApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        menuPanel.setBackground(new java.awt.Color(165, 178, 243));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSignIn.setBackground(new java.awt.Color(165, 178, 243));
        PanelSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSignInMousePressed(evt);
            }
        });
        PanelSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loggin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Loggin.setForeground(new java.awt.Color(255, 255, 255));
        Loggin.setText("Sign In");
        PanelSignIn.add(Loggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 11, -1, -1));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_User_32px.png"))); // NOI18N
        iconLabel.setToolTipText("");
        PanelSignIn.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jUsername.setText("username");
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        PanelSignIn.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 62, 111, 30));

        jPassword.setText("password");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        PanelSignIn.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 104, 111, 30));

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password");
        PanelSignIn.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 103, -1, -1));

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username");
        PanelSignIn.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 61, -1, -1));

        buttonSignin.setBackground(new java.awt.Color(111, 134, 243));
        buttonSignin.setText("Sign In");
        buttonSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSigninActionPerformed(evt);
            }
        });
        PanelSignIn.add(buttonSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 29));

        menuPanel.add(PanelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        PanelSignUP.setBackground(new java.awt.Color(165, 178, 243));
        PanelSignUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSignUPMousePressed(evt);
            }
        });
        PanelSignUP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Add_User_Male_32px.png"))); // NOI18N
        iconLabel1.setToolTipText("");
        PanelSignUP.add(iconLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        Loggin1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Loggin1.setForeground(new java.awt.Color(255, 255, 255));
        Loggin1.setText("Sign Up");
        PanelSignUP.add(Loggin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));

        menuPanel.add(PanelSignUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 330, 60));

        PanelStatistic.setBackground(new java.awt.Color(165, 178, 243));
        PanelStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelStatisticMousePressed(evt);
            }
        });
        PanelStatistic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Statistics_32px_2.png"))); // NOI18N
        iconAbout1.setToolTipText("");
        PanelStatistic.add(iconAbout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        about1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about1.setForeground(new java.awt.Color(255, 255, 255));
        about1.setText("Statistic");
        PanelStatistic.add(about1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));

        menuPanel.add(PanelStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 330, 60));

        PanelAbout.setBackground(new java.awt.Color(165, 178, 243));
        PanelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelAboutMousePressed(evt);
            }
        });
        PanelAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Info_32px.png"))); // NOI18N
        iconAbout.setToolTipText("");
        PanelAbout.add(iconAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        about.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("About");
        PanelAbout.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));

        menuPanel.add(PanelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 330, 60));

        sidePanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 570));

        BG.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 683));

        homePanel.setBackground(new java.awt.Color(101, 153, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/background.png"))); // NOI18N
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(204, 51, 0));

        homepage.setBackground(new java.awt.Color(0, 51, 102));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Logo.png"))); // NOI18N
        homepage.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        deskripsi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deskripsi1.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi1.setText("KosQu adalah aplikasi yang dapat memberikan informasi dan rekomendasi");
        homepage.add(deskripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        deskripsi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deskripsi2.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi2.setText("tempat kos yang ada di kota bandung");
        homepage.add(deskripsi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabel3.setText("jLabel3");
        homepage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 904, -1, -1));

        judulApp1.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        judulApp1.setForeground(new java.awt.Color(255, 255, 255));
        judulApp1.setText("KosQu");
        homepage.add(judulApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jScrollPane2.setViewportView(homepage);

        homePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 690));

        BG.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, -5, 790, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void buttonSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSigninActionPerformed
//        // TODO add your handling code here:
        String isi;
        int i = 1;
        int passIn;
        String accType;
        boolean run = true;

        //set value
        setNamaDepan(jUsername.getText());
        setPassword(jPassword.getText());

        // read excel
        FileInputStream fis = null;
        try {
            fis = new FileInputStream("src/data/UserData.xlsx");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        Workbook wb = null;
        try {
            wb = new XSSFWorkbook(fis);
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        Sheet sh = wb.getSheet("Sheet1");
        int noOfRow = sh.getLastRowNum();
        System.out.println(noOfRow);

        for (Iterator<Row> rit = sh.rowIterator(); rit.hasNext();) {
            Row row = rit.next();
            for (Iterator<Cell> cit = row.cellIterator(); cit.hasNext();) {
                Cell cell = cit.next();
                System.out.println("Username - input : " + getNamaDepan());
                System.out.println("Username - database: " + row.getCell(0));
                System.out.println("Password - input : " + getPassword());
                System.out.println("Password - database : " + row.getCell(1));

                System.out.println("Dilakukan pemeriksaan");
//            System.out.println(getNamaDepan().equals(row.getCell(0)));

                if (getNamaDepan().equals(getCellValueAsString(row.getCell(0)))) {
                    System.out.println("Username MATCH !");
                    if (getPassword().equals(getCellValueAsString(row.getCell(1)))) {
                        System.out.println("Username and Password MATCH !");
                        Point Coords = this.getLocationOnScreen();
                        this.dispose();
                        new Dashboard().setVisible(true);
                        
                        accType = getCellValueAsString(row.getCell(2));
                        CreateDialogFromOptionPane("You're login as " + accType + "kos");
                    } else {
                        System.out.println("Password NOT MATCH !");
                    }

                } else {
                    System.out.println("Username NOT MATCH !");
                }
                // Print the each cell value
                System.out.println("Output : " + getCellValueAsString(cell));
            }
        }
        CreateDialogFromOptionPane("Username or Password NOT FOUND !");
        System.out.println("Keluar dari loop");
    }//GEN-LAST:event_buttonSigninActionPerformed

    private void PanelSignUPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSignUPMousePressed
        //@author Imanda_Syahrul_Ramadhan
        // TODO add your handling code here:
        setColor(PanelSignUP);
        resetColor(PanelSignIn);
        resetColor(PanelAbout);
        resetColor(PanelStatistic);
        new FormSignUp().setVisible(true);
    }//GEN-LAST:event_PanelSignUPMousePressed

    private void PanelAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAboutMousePressed
        //@author Imanda_Syahrul_Ramadhan
        // TODO add your handling code here:
        setColor(PanelAbout);
        resetColor(PanelSignIn);
        resetColor(PanelSignUP);
        resetColor(PanelStatistic);
        new About().setVisible(true);
    }//GEN-LAST:event_PanelAboutMousePressed

    private void PanelSignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSignInMousePressed
        //@author Imanda_Syahrul_Ramadhan
        // TODO add your handling code here:
        if (PanelSignIn.getBackground().equals(new Color(165, 178, 243))) {
            setColor(PanelSignIn);
            resetColor(PanelSignUP);
            resetColor(PanelAbout);
            resetColor(PanelStatistic);
            PanelSignIn.setSize(330, 180);
            PanelSignUP.setLocation(0, 180);
            PanelStatistic.setLocation(0, 240);
            PanelAbout.setLocation(0, 300);
        } else {
            resetColor(PanelSignIn);
            PanelSignIn.setSize(330, 60);
            PanelSignUP.setLocation(0, 60);
            PanelStatistic.setLocation(0, 120);
            PanelAbout.setLocation(0, 180);
        }
    }//GEN-LAST:event_PanelSignInMousePressed

    private void PanelStatisticMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelStatisticMousePressed
        // TODO add your handling code here:
        setColor(PanelStatistic);
        resetColor(PanelSignUP);
        resetColor(PanelAbout);
        resetColor(PanelSignIn);
        new BarChart().setVisible(true);
    }//GEN-LAST:event_PanelStatisticMousePressed

    //@author Imanda_Syahrul_Ramadhan
    void setColor(JPanel panel) {
        panel.setBackground(new Color(140, 158, 243));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(165, 178, 243));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
//        RunnableImpl run = new RunnableImpl();
//        run.run();        
    }

    private String getCellValueAsString(Cell cell) {
        String strCellValue = null;
        if (cell != null) {
            switch (cell.getCellType()) {
                case Cell.CELL_TYPE_STRING:
                    strCellValue = cell.toString();
                    break;
                case Cell.CELL_TYPE_NUMERIC:
                    if (DateUtil.isCellDateFormatted(cell)) {
                        SimpleDateFormat dateFormat = new SimpleDateFormat(
                                "dd/MM/yyyy");
                        strCellValue = dateFormat.format(cell.getDateCellValue());
                    } else {
                        Double value = cell.getNumericCellValue();
                        Long longValue = value.longValue();
                        strCellValue = new String(longValue.toString());
                    }
                    break;
                case Cell.CELL_TYPE_BOOLEAN:
                    strCellValue = new String(new Boolean(
                            cell.getBooleanCellValue()).toString());
                    break;
                case Cell.CELL_TYPE_BLANK:
                    strCellValue = "";
                    break;
            }
        }
        return strCellValue;
    }
    
    private void CreateDialogFromOptionPane(String show) {
        
        JFrame parent = new JFrame();
        JOptionPane.showMessageDialog(parent, show);
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {

        }

        public void run() {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            new StartGUI().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Loggin;
    private javax.swing.JLabel Loggin1;
    private javax.swing.JPanel PanelAbout;
    private javax.swing.JPanel PanelSignIn;
    private javax.swing.JPanel PanelSignUP;
    private javax.swing.JPanel PanelStatistic;
    private javax.swing.JLabel about;
    private javax.swing.JLabel about1;
    private javax.swing.JButton buttonSignin;
    private javax.swing.JLabel deskripsi1;
    private javax.swing.JLabel deskripsi2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel iconAbout;
    private javax.swing.JLabel iconAbout1;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jUsername;
    private javax.swing.JLabel judulApp;
    private javax.swing.JLabel judulApp1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the namaDepan
     */
    public String getNamaDepan() {
        return namaDepan;
    }

    /**
     * @param namaDepan the namaDepan to set
     */
    public void setNamaDepan(String namaDepan) {
        this.namaDepan = namaDepan;
    }

    /**
     * @return the namaBelakang
     */
    public String getNamaBelakang() {
        return namaBelakang;
    }

    /**
     * @param namaBelakang the namaBelakang to set
     */
    public void setNamaBelakang(String namaBelakang) {
        this.namaBelakang = namaBelakang;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the alamat
     */
    public String getAlamat() {
        return alamat;
    }

    /**
     * @param alamat the alamat to set
     */
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    /**
     * @return the jenisAkun
     */
    public String getJenisAkun() {
        return jenisAkun;
    }

    /**
     * @param jenisAkun the jenisAkun to set
     */
    public void setJenisAkun(String jenisAkun) {
        this.jenisAkun = jenisAkun;
    }
}
