/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage2;

import Barchart.data;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Imanda Syahrul R
 */
public class Statistic extends javax.swing.JFrame {

    /**
     * Creates new form Statistic
     */
    public Statistic() {
        initComponents();
    }
    
    // Bar Chart
    public static JPanel createBarChartPanel1(){
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }
        
        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);
        
        return new ChartPanel(chart);
    }
    
    public static JPanel createBarChartPanel2(){
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }
        
        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);
        
        return new ChartPanel(chart);
    }
    
    public static JPanel createBarChartPanel3(){
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            barDataset.setValue(daftar.get(i).getInfo(), "", daftar.get(i).getTitle());
        }
        
        JFreeChart chart = ChartFactory.createBarChart3D("Kost Berdasarkan Kecamatan", "Kecamatan", "Jumlah", barDataset, PlotOrientation.VERTICAL, true, true, false);
        
        return new ChartPanel(chart);
    }

    // Pie Chart
    public static JPanel createPieChartPanel1(){
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            pieDataset.setValue(daftar.get(i).getTitle(), daftar.get(i).getInfo());
        }
        JFreeChart chart = ChartFactory.createPieChart3D("Kost Berdasarkan Gender", pieDataset, true, true, true);
        
        return new ChartPanel(chart);
    }
    
    public static JPanel createPieChartPanel2(){
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        List<data> daftar = new ArrayList<>();
        
        for (int i = 0; i < 10; i++) {
            data e = new data();
            e.setInfo(10);
            e.setTitle("eee" + i);
            daftar.add(i, e);
        }
        
        for (int i = 0; i < daftar.size(); i++) {
            pieDataset.setValue(daftar.get(i).getTitle(), daftar.get(i).getInfo());
        }
        JFreeChart chart = ChartFactory.createPieChart3D("Kost Berdasarkan Range Harga", pieDataset, true, true, true);
        
        return new ChartPanel(chart);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
