/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * @author Imanda Syahrul R
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        ButtonGroup TipeKost = new ButtonGroup();
        TipeKost.add(jRadioButton1);
        TipeKost.add(jRadioButton2);
        TipeKost.add(jRadioButton3);
        
        ButtonGroup RangeHarga = new ButtonGroup();
        RangeHarga.add(jRadioButton4);
        RangeHarga.add(jRadioButton5);
        RangeHarga.add(jRadioButton6);
        RangeHarga.add(jRadioButton7);
        RangeHarga.add(jRadioButton8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        PanelLogout = new javax.swing.JPanel();
        iconLogout1 = new javax.swing.JLabel();
        Logout1 = new javax.swing.JLabel();
        judulApp = new javax.swing.JLabel();
        PanelFilter = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        Loggin1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        PanelStatistic = new javax.swing.JPanel();
        iconAbout1 = new javax.swing.JLabel();
        about1 = new javax.swing.JLabel();
        PanelBookmark = new javax.swing.JPanel();
        iconLogout = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        PanelSetting = new javax.swing.JPanel();
        iconAbout = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        basedOn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        basedOn1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        basedOn3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1119, 685));

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(165, 178, 243));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogout.setBackground(new java.awt.Color(165, 178, 243));
        PanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelLogoutMousePressed(evt);
            }
        });

        iconLogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Logout_Rounded_Up_32px_1.png"))); // NOI18N
        iconLogout1.setToolTipText("");

        Logout1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Logout1.setForeground(new java.awt.Color(255, 255, 255));
        Logout1.setText("Sign Out");

        javax.swing.GroupLayout PanelLogoutLayout = new javax.swing.GroupLayout(PanelLogout);
        PanelLogout.setLayout(PanelLogoutLayout);
        PanelLogoutLayout.setHorizontalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconLogout1)
                .addGap(6, 6, 6)
                .addComponent(Logout1))
        );
        PanelLogoutLayout.setVerticalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconLogout1))
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logout1))
        );

        sidePanel.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 330, 60));

        judulApp.setBackground(new java.awt.Color(0, 51, 102));
        judulApp.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        judulApp.setForeground(new java.awt.Color(255, 255, 255));
        judulApp.setText("KosQu");
        sidePanel.add(judulApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelFilter.setBackground(new java.awt.Color(165, 178, 243));
        PanelFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelFilterMousePressed(evt);
            }
        });
        PanelFilter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Filter_32px.png"))); // NOI18N
        iconLabel1.setToolTipText("");
        PanelFilter.add(iconLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        Loggin1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Loggin1.setForeground(new java.awt.Color(255, 255, 255));
        Loggin1.setText("Filter");
        PanelFilter.add(Loggin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));

        jPanel1.setBackground(new java.awt.Color(140, 158, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(140, 158, 243));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipe");

        jRadioButton1.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Pria");

        jRadioButton2.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Wanita");

        jRadioButton3.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Campuran");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 310, 140));

        jPanel7.setBackground(new java.awt.Color(140, 158, 243));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Range Harga");

        jRadioButton4.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText(">500.000");

        jRadioButton5.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("500.000 - 750.000");

        jRadioButton6.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("750.000 - 1.000.000");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("1.000.000 - 1.500.000");

        jRadioButton8.setBackground(new java.awt.Color(140, 158, 243));
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText(">1.500.000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton4))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addGap(3, 3, 3)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, 170));

        jScrollPane4.setViewportView(jPanel1);

        PanelFilter.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 330, 239));

        sidePanel.add(PanelFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 60));

        PanelStatistic.setBackground(new java.awt.Color(165, 178, 243));
        PanelStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelStatisticMousePressed(evt);
            }
        });

        iconAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Statistics_32px_2.png"))); // NOI18N
        iconAbout1.setToolTipText("");

        about1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about1.setForeground(new java.awt.Color(255, 255, 255));
        about1.setText("Statistic");

        javax.swing.GroupLayout PanelStatisticLayout = new javax.swing.GroupLayout(PanelStatistic);
        PanelStatistic.setLayout(PanelStatisticLayout);
        PanelStatisticLayout.setHorizontalGroup(
            PanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatisticLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconAbout1)
                .addGap(6, 6, 6)
                .addComponent(about1))
        );
        PanelStatisticLayout.setVerticalGroup(
            PanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatisticLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconAbout1))
            .addGroup(PanelStatisticLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(about1))
        );

        sidePanel.add(PanelStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 330, 60));

        PanelBookmark.setBackground(new java.awt.Color(165, 178, 243));
        PanelBookmark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBookmarkMousePressed(evt);
            }
        });

        iconLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Bookmark_Ribbon_32px_2.png"))); // NOI18N
        iconLogout.setToolTipText("");

        Logout.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Bookmark");

        javax.swing.GroupLayout PanelBookmarkLayout = new javax.swing.GroupLayout(PanelBookmark);
        PanelBookmark.setLayout(PanelBookmarkLayout);
        PanelBookmarkLayout.setHorizontalGroup(
            PanelBookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookmarkLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconLogout)
                .addGap(6, 6, 6)
                .addComponent(Logout))
        );
        PanelBookmarkLayout.setVerticalGroup(
            PanelBookmarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookmarkLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconLogout))
            .addGroup(PanelBookmarkLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logout))
        );

        sidePanel.add(PanelBookmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 60));

        PanelSetting.setBackground(new java.awt.Color(165, 178, 243));
        PanelSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSettingMousePressed(evt);
            }
        });

        iconAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Settings_32px.png"))); // NOI18N
        iconAbout.setToolTipText("");

        about.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("Account Setting");

        javax.swing.GroupLayout PanelSettingLayout = new javax.swing.GroupLayout(PanelSetting);
        PanelSetting.setLayout(PanelSettingLayout);
        PanelSettingLayout.setHorizontalGroup(
            PanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconAbout)
                .addGap(6, 6, 6)
                .addComponent(about))
        );
        PanelSettingLayout.setVerticalGroup(
            PanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconAbout))
            .addGroup(PanelSettingLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(about))
        );

        sidePanel.add(PanelSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 330, 60));

        BG.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 683));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basedOn.setBackground(new java.awt.Color(204, 255, 255));
        basedOn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Based On");
        basedOn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        jScrollPane2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        basedOn.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 180));

        jPanel2.add(basedOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 67, 638, 213));

        basedOn1.setBackground(new java.awt.Color(204, 255, 255));
        basedOn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("Based On");
        basedOn1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        jScrollPane3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel4);

        basedOn1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 180));

        jPanel2.add(basedOn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 374, -1, -1));

        basedOn3.setBackground(new java.awt.Color(204, 255, 255));
        basedOn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("jLabel1");
        basedOn3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        jScrollPane5.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jPanel6);

        basedOn3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 180));

        jPanel2.add(basedOn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 674, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        BG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 790, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelFilterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelFilterMousePressed
        //@author Imanda_Syahrul_Ramadhan
        // TODO add your handling code here:
        if(PanelFilter.getBackground().equals(new Color(165,178,243))){
            setColor(PanelFilter);
            resetColor(PanelSetting);
            resetColor(PanelBookmark);
            resetColor(PanelStatistic);
            resetColor(PanelLogout);
            PanelFilter.setSize(330, 300);
            PanelBookmark.setLocation(0, 410);
            PanelSetting.setLocation(0, 530);
            PanelStatistic.setLocation(0, 470);
            PanelLogout.setLocation(0, 590);
        }
        else{
            resetColor(PanelFilter);
            PanelFilter.setSize(330, 60);
            PanelBookmark.setLocation(0, 110);
            PanelSetting.setLocation(0, 170);
            PanelStatistic.setLocation(0, 230);
            PanelLogout.setLocation(0, 290);
        }
        
        
    }//GEN-LAST:event_PanelFilterMousePressed

    private void PanelStatisticMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelStatisticMousePressed
        // TODO add your handling code here:
        setColor(PanelStatistic);
        resetColor(PanelFilter);
        resetColor(PanelSetting);
        resetColor(PanelLogout);
        resetColor(PanelBookmark);
    }//GEN-LAST:event_PanelStatisticMousePressed

    private void PanelSettingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSettingMousePressed
        //@author Imanda_Syahrul_Ramadhan
        // TODO add your handling code here:
        setColor(PanelSetting);
        resetColor(PanelLogout);
        resetColor(PanelBookmark);
        resetColor(PanelFilter);
        resetColor(PanelStatistic);
    }//GEN-LAST:event_PanelSettingMousePressed

    private void PanelBookmarkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBookmarkMousePressed
        // TODO add your handling code here:
        setColor(PanelBookmark);
        resetColor(PanelFilter);
        resetColor(PanelSetting);
        resetColor(PanelLogout);
        resetColor(PanelStatistic);
    }//GEN-LAST:event_PanelBookmarkMousePressed

    private void PanelLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogoutMousePressed
        // TODO add your handling code here:
        this.dispose();
        new StartGUI().setVisible(true);
    }//GEN-LAST:event_PanelLogoutMousePressed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    //@author Imanda_Syahrul_Ramadhan
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(140,158,243));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(165,178,243));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Loggin1;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Logout1;
    private javax.swing.JPanel PanelBookmark;
    private javax.swing.JPanel PanelFilter;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelSetting;
    private javax.swing.JPanel PanelStatistic;
    private javax.swing.JLabel about;
    private javax.swing.JLabel about1;
    private javax.swing.JPanel basedOn;
    private javax.swing.JPanel basedOn1;
    private javax.swing.JPanel basedOn3;
    private javax.swing.JLabel iconAbout;
    private javax.swing.JLabel iconAbout1;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel iconLogout;
    private javax.swing.JLabel iconLogout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel judulApp;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
