/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ahmad_Aji_Naufal_Ali
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        PanelSignIn = new javax.swing.JPanel();
        Loggin = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jUsername = new javax.swing.JFormattedTextField();
        jPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        buttonSignin = new javax.swing.JButton();
        judulApp = new javax.swing.JLabel();
        PanelSignUP = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        Loggin1 = new javax.swing.JLabel();
        PanelAbout = new javax.swing.JPanel();
        iconAbout = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        homepage = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        deskripsi1 = new javax.swing.JLabel();
        deskripsi2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judulApp1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSignIn.setBackground(new java.awt.Color(140, 158, 243));

        Loggin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Loggin.setForeground(new java.awt.Color(255, 255, 255));
        Loggin.setText("Sign In");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_User_32px.png"))); // NOI18N
        iconLabel.setToolTipText("");

        jUsername.setText("username");
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });

        jPassword.setText("password");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password");

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username");

        buttonSignin.setText("Sign In");
        buttonSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSignInLayout = new javax.swing.GroupLayout(PanelSignIn);
        PanelSignIn.setLayout(PanelSignInLayout);
        PanelSignInLayout.setHorizontalGroup(
            PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSignInLayout.createSequentialGroup()
                        .addComponent(iconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Loggin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSignInLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonSignin)
                            .addGroup(PanelSignInLayout.createSequentialGroup()
                                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSignInLayout.createSequentialGroup()
                                        .addComponent(labelUsername)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(PanelSignInLayout.createSequentialGroup()
                                        .addComponent(labelPassword)
                                        .addGap(18, 18, 18)))
                                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jUsername))))
                        .addGap(95, 95, 95))))
        );
        PanelSignInLayout.setVerticalGroup(
            PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel)
                    .addComponent(Loggin))
                .addGap(18, 18, 18)
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(PanelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 330, 180));

        judulApp.setBackground(new java.awt.Color(0, 51, 102));
        judulApp.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        judulApp.setForeground(new java.awt.Color(0, 51, 102));
        judulApp.setText("KosQu");
        sidePanel.add(judulApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelSignUP.setBackground(new java.awt.Color(165, 178, 243));

        iconLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Add_User_Male_32px.png"))); // NOI18N
        iconLabel1.setToolTipText("");

        Loggin1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Loggin1.setForeground(new java.awt.Color(255, 255, 255));
        Loggin1.setText("Sign Up");

        javax.swing.GroupLayout PanelSignUPLayout = new javax.swing.GroupLayout(PanelSignUP);
        PanelSignUP.setLayout(PanelSignUPLayout);
        PanelSignUPLayout.setHorizontalGroup(
            PanelSignUPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignUPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Loggin1)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        PanelSignUPLayout.setVerticalGroup(
            PanelSignUPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSignUPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSignUPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Loggin1)
                    .addComponent(iconLabel1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        sidePanel.add(PanelSignUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 330, 60));

        PanelAbout.setBackground(new java.awt.Color(165, 178, 243));

        iconAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/icons8_Info_32px.png"))); // NOI18N
        iconAbout.setToolTipText("");

        about.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("About");

        javax.swing.GroupLayout PanelAboutLayout = new javax.swing.GroupLayout(PanelAbout);
        PanelAbout.setLayout(PanelAboutLayout);
        PanelAboutLayout.setHorizontalGroup(
            PanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        PanelAboutLayout.setVerticalGroup(
            PanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(about)
                    .addComponent(iconAbout))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        sidePanel.add(PanelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 330, 60));

        BG.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 683));

        homePanel.setBackground(new java.awt.Color(101, 153, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/background.png"))); // NOI18N
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(204, 51, 0));

        homepage.setBackground(new java.awt.Color(0, 51, 102));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Logo.png"))); // NOI18N
        homepage.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        deskripsi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deskripsi1.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi1.setText("KosQu adalah aplikasi yang dapat memberikan informasi dan rekomendasi");
        homepage.add(deskripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        deskripsi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deskripsi2.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi2.setText("tempat kos yang ada di kota bandung");
        homepage.add(deskripsi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabel3.setText("jLabel3");
        homepage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 904, -1, -1));

        judulApp1.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        judulApp1.setForeground(new java.awt.Color(255, 255, 255));
        judulApp1.setText("KosQu");
        homepage.add(judulApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jScrollPane2.setViewportView(homepage);

        homePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 690));

        BG.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, -5, 790, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void buttonSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSigninActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
//        RunnableImpl run = new RunnableImpl();
//        run.run();        
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
            
        }

        public void run() {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            new StartGUI().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Loggin;
    private javax.swing.JLabel Loggin1;
    private javax.swing.JPanel PanelAbout;
    private javax.swing.JPanel PanelSignIn;
    private javax.swing.JPanel PanelSignUP;
    private javax.swing.JLabel about;
    private javax.swing.JButton buttonSignin;
    private javax.swing.JLabel deskripsi1;
    private javax.swing.JLabel deskripsi2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel iconAbout;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jUsername;
    private javax.swing.JLabel judulApp;
    private javax.swing.JLabel judulApp1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
